### PR TITLE
Fix position desync between clients

### LINKED ISSUE #363: Teleport de-sync
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Manjaro Linux

### Server Software Version/Commit

f29cfbc

### What happened?

Player position gets de-synced between clients when teleporting more than 8 blocks. This results in the player falling through the ground on other players POV.

### To Reproduce

/teleport ~ ~10 ~
You should then be in the ground for other players when falling to the ground.

### Expected behavior

Teleport 10 blocks up and then fall down stopping at the ground for all players.

### PR DESCRIPTION
**Pull request by Alvsch**
## Description
This PR makes sure the player position isn't desynced between players when moving too fast (>8 blocks/tick).
Also fixes `/tp` desync (Fixes #363)  

## Testing
Two minecraft players looking at each other
- `/tp ~ ~10 ~` and make sure no weird stuff happens
- Move faster than 8 blocks and make sure no weird stuff happens (hacked clients are good for this)

Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guidelines)

### CODE REVIEW

File: pumpkin-protocol/src/client/play/synchronize_vehicle_position.rs [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+use crate::{
+    ClientPacket, PositionFlag, VarInt,
+    ser::{NetworkWriteExt, WritingError},
+};
+
+// https://minecraft.wiki/w/Java_Edition_protocol#Synchronize_Vehicle_Position
+// Badly documented and confusing packet imo
+#[packet(PLAY_TELEPORT_ENTITY)]
+pub struct CSynchronizeVehiclePosition<'a> {
```
Comment (Snowiiii) [inline pumpkin-protocol/src/client/play/synchronize_vehicle_position.rs:15]: Why is this called `CSynchronizeVehiclePosition` ? also we already have a packet called `CTeleportEntity`

Comment (Alvsch) [reply pumpkin-protocol/src/client/play/synchronize_vehicle_position.rs:15]: check out the linked docs, idk everything is very confusing

Comment (Alvsch) [reply pumpkin-protocol/src/client/play/synchronize_vehicle_position.rs:15]: they renamed the packet resources in 1.21 or smth

**Comment by Snowiiii** [comment]
Looks good. Nice to have that finally fixed. Thank you @Alvsch

**Comment by zly2006** [comment]
Hi, I disagree with this PR. I think the packets naming should follow mojang's names, so relatives should be in CTeleportEntity. Accordingly, another packet (the new CTeleportEntity after this PR) should be named CEntityPositionSync.

In fact, the original CTeleportEntity is the packet sent when calling player.teleport in vanilla, CSynchronizeVehiclePosition totally makes no sense.
