### PR TITLE
Store equipment and level.dat correctly

### LINKED ISSUE #1019: anvil world format world summary missing
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Windows 11

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.7 (f400a5d2)

### What happened?

Image

### To Reproduce

Create a world using pumpkin and then try to load it from the vanilla minecraft client.

### Expected behavior

(The same with the vanilla micecraft server)
Image

### PR DESCRIPTION
**Pull request by Commandcracker**
## Description
resolves #1019, #1018
Ther are still some issues but now it is atleast possible

## Testing

Created world from pumkin and loaded it in vanilla minecraft client and server

Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guidelines)

### CODE REVIEW

**Comment by TheDarkSword** [comment]
What issues are still remaining?

**Comment by Commandcracker** [comment]
equipment is not correctly stored

In pumpkin:
grafik
grafik
When loading from vanilla
grafik
grafik
How it should be
grafik
grafik


You cant move some player atributes are not correct
grafik

**Comment by Commandcracker** [comment]
grafik
grafik

**Comment by TheDarkSword** [comment]
If you want you can fix these issues in this pull request, as are correlated with the problem

**Comment by Commandcracker** [comment]
should'nt we set a correct fallback if reading fails and maby also log if it fails ?

```rs
    async fn read_nbt(&mut self, nbt: &mut NbtCompound) {
        if let Some(component) = nbt.get_compound("abilities") {
            self.invulnerable = component.get_bool("invulnerable").unwrap_or(false);
            self.flying = component.get_bool("flying").unwrap_or(false);
            self.allow_flying = component.get_bool("mayfly").unwrap_or(false);
            self.creative = component.get_bool("instabuild").unwrap_or(false);
            self.allow_modify_world = component.get_bool("mayBuild").unwrap_or(false);
            self.fly_speed = component.get_float("flySpeed").unwrap_or(0.0);
            self.walk_speed = component.get_float("walkSpeed").unwrap_or(0.0);
        }
    }
}

impl Default for Abilities {
    fn default() -> Self {
        Self {
            invulnerable: false,
            flying: false,
            allow_flying: false,
            creative: false,
            allow_modify_world: true,
            fly_speed: 0.05,
            walk_speed: 0.1,
        }
    }
}
```

**Comment by TheDarkSword** [comment]
When I implemented the NBTStorage for Effect, I added a console warning if something isn't read correctly. If you want, you can do the same, and for data that's absolutely essential (like walk_speed), always provide a default value

File: pumpkin-world/src/world_info/mod.rs [hunk 1]
```diff
@@ -14,6 +15,11 @@ pub mod anvil;
 pub const MINIMUM_SUPPORTED_WORLD_DATA_VERSION: i32 = 4435; // 1.21.7
 pub const MAXIMUM_SUPPORTED_WORLD_DATA_VERSION: i32 = 4438; // 1.21.7
 
+pub const MINIMUM_SUPPORTED_LEVEL_VERSION: i32 = 19132; // 1.21.7
+pub const MAXIMUM_SUPPORTED_LEVEL_VERSION: i32 = 19133; // 1.21.7
+
+pub const CURRENT_MC_VERSION: &str = "1.21.7";
```
Comment (Snowiiii) [inline pumpkin-world/src/world_info/mod.rs]: We already have that?

Comment (Commandcracker) [reply pumpkin-world/src/world_info/mod.rs]: yes but i cant import pumpkin

Comment (Commandcracker) [reply pumpkin-world/src/world_info/mod.rs]: should i make a package where we store globas consts ?

Comment (TheDarkSword) [reply pumpkin-world/src/world_info/mod.rs:21]: > yes but i cant import pumpkin

You have to import crate::(…) not pumpkin::(…)

Comment (Commandcracker) [reply pumpkin-world/src/world_info/mod.rs]: but CURRENT_MC_VERSION is in a differnt crate 

error: cyclic package dependency: package `pumpkin v0.1.0-dev+1.21.7 (...)` depends on itself. Cycle:
package `pumpkin v0.1.0-dev+1.21.7 (...)`
    ... which satisfies path dependency `pumpkin` (locked to 0.1.0-dev+1.21.7) of package `pumpkin-world v0.1.0-dev+1.21.7 (...)`
    ... which satisfies path dependency `pumpkin-world` (locked to 0.1.0-dev+1.21.7) of package `pumpkin-protocol v0.1.0-dev+1.21.7 (...)`
    ... which satisfies path dependency `pumpkin-protocol` (locked to 0.1.0-dev+1.21.7) of package `pumpkin-inventory v0.1.0-dev+1.21.7 (...)`
    ... which satisfies path dependency `pumpkin-inventory` (locked to 0.1.0-dev+1.21.7) of package `pumpkin v0.1.0-dev+1.21.7 (...)`
    
im confused

Comment (TheDarkSword) [reply pumpkin-world/src/world_info/mod.rs]: Yes you are right, maybe these constants can be moved in another crate as you said

**Comment by Snowiiii** [comment]
Please remove all the logging, Vanilla does not do that, And also it will be super annoying when updating the player files

**Comment by TheDarkSword** [comment]
> Please remove all the logging, Vanilla does not do that, And also it will be super annoying when updating the player files

I think they are useful because these type of data don’t change name usually, maybe is better Debug instead of Warn?

**Comment by Snowiiii** [comment]
```
thread 'main' panicked at /home/alex/Documents/Development/Rust/Pumpkin/pumpkin/src/server/mod.rs:142:21:
      World Error Deserialization error: Serde error: missing field `dimensions`
                                                                                note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``

**Comment by Snowiiii** [comment]
@Commandcracker any progress ?

**Comment by Commandcracker** [comment]
It works it is just that it is incompatibile with old pumkin worlds because they are missing "level version" in level.data (including some other things that changed)

**Comment by Snowiiii** [comment]
LGTM. Thank you @Commandcracker 🦙
