### PR TITLE
Fix LZ4 algorithm

### LINKED ISSUE #792: LZ4 algorithm is different from vanilla
Mojang used a non standard lz4 format that only exists in java lz4 library, called "Streaming LZ4", and lz4-rs uses standard frame based streaming, which is used in pumpkin.

"Streaming LZ4" javadoc: https://lz4.github.io/lz4-java/1.8.0/docs/net/jpountz/lz4/LZ4BlockOutputStream.html
Implementation guide (not exact implementation, we have to follow lz4-java's code): https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md

Since they are different formats of LZ4, the saves are impossible to load across pumpkin and vanilla. We have to implement a custom lz4 encoder/decoder to match vanilla.

### PR DESCRIPTION
**Pull request by zly2006**
## Description

Fix #792 by replacing lz4-rs compression with lz4-java-wrc to match vanilla behavior.

## Testing

✅  Load Java save in pumpkin
✅  Load pumpkin save in Java

Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guidelines)

### CODE REVIEW

File: pumpkin-world/src/chunk/format/anvil.rs [hunk 1]
```diff
@@ -188,19 +189,23 @@ impl Compression {
...
                 Ok(chunk_data)
             }
-
             Compression::LZ4 => {
                 let mut compressed_data = Vec::new();
-                let mut encoder = lz4::EncoderBuilder::new()
-                    .level(compression_level)
-                    .build(&mut compressed_data)
-                    .map_err(CompressionError::LZ4Error)?;
+                let block_size = if compression_level == 0 {
```
Comment (kralverde) [inline pumpkin-world/src/chunk/format/anvil.rs:194]: Is this documented anywhere in LZ4 or did you just come up with it?

**Review by kralverde — CHANGES_REQUESTED** [review]

**Comment by Snowiiii** [comment]
I would like to have #787 merged first

**Comment by kralverde** [comment]
Yes

File: pumpkin-world/src/chunk/format/anvil.rs (hunk 1 above)
Comment (zly2006) [reply pumpkin-world/src/chunk/format/anvil.rs:194]: https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/lz4/LZ4BlockOutputStream.java#L58
Its based on the code here.

**Comment by zly2006** [comment]
> I would like to have #787 merged first

Sure

**Comment by Snowiiii** [comment]
@zly2006 lets switch to the master branch

**Comment by zly2006** [comment]
There is no conflict so it can be merged

**Comment by Q2297045667** [comment]
@Snowiiii I haven't found any issues so far. I think it should be possible to merge.

**Comment by Snowiiii** [comment]
Nice everything works now. Thank you @zly2006 :D :camel:
